server.port=8090

spring.application.name=board
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=88toaanf!@#X88
spring.datasource.url=jdbc:mysql://localhost:3306/board