spring:
  application:
    name: board-main-api
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        connection:
          provider_disables_autocommit: true
    open-in-view: false
    generate-ddl: false
    show-sql: true

jwt:
  token:
    expiration_time: 3600000    # 1시간
    secret: nTyqckgwTkObL3Kwiw9nO6d4HQ15dxeKnuCeOF8taS3PZFOv

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/board?autoReconnect=true&characterEncoding=UTF-8
    username: boarduser
    password: boardPassword
    hikari:
      maximum-pool-size: 50
      max-lifetime: 28798000
      auto-commit: false
      connection-timeout: 10000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      leak-detection-threshold: 5000

  data:
    redis:
      port: 6379
      host: localhost
      password:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
    mongodb:
      host: localhost
      port: 27017
      username: boarduser
      password: boardPassword
      database: board

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
  show-login-endpoint: true
  override-with-generic-response: false

server:
  port: 64280

logging:
  level:
    root: error
    com.project.board.main.api: debug
    org.hibernate.resource: info
    com.zaxxer.hikari.pool.HikariPool: debug
    com.zaxxer.hikari: trace
  dir: E:\data\workSpace\sampleData\board\logs
#  dir: /Users/kimdy/data/workSpace/sampleData/board/logs

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?autoReconnect=true&characterEncoding=UTF-8
    username: boarduser
    password: boardPassword
    hikari:
      maximum-pool-size: 50
      max-lifetime: 28798000
      auto-commit: false
      connection-timeout: 10000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      leak-detection-threshold: 5000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  data:
    redis:
      port: 6379
      host: localhost
      password:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
    mongodb:
      host: localhost
      port: 27017
      username: boarduser
      password: boardPassword
      database: board

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
  show-login-endpoint: true
  override-with-generic-response: false

server:
  port: 64280

logging:
  level:
    root: error
    com.project.board.main.api: debug
    org.hibernate.resource: info
    com.zaxxer.hikari.pool.HikariPool: debug
    com.zaxxer.hikari: trace
  dir: /data/board/logs

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?autoReconnect=true&characterEncoding=UTF-8
    username: boarduser
    password: boardPassword
    hikari:
      maximum-pool-size: 50
      max-lifetime: 28798000
      auto-commit: false
      connection-timeout: 10000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      leak-detection-threshold: 5000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  data:
    redis:
      port: 6379
      host: localhost
      password:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
    mongodb:
      host: localhost
      port: 27017
      username: boarduser
      password: boardPassword
      database: board

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

server:
  port: 64280

logging:
  level:
    root: error
    com.project.board.main.api: debug
    org.hibernate.resource: info
    com.zaxxer.hikari.pool.HikariPool: debug
    com.zaxxer.hikari: trace
  dir: /data/board/logs